services:
  elasticsearch:
    build: ./elasticsearch
    container_name: reactor-elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - reactor-net
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  logstash:
    build: ./logstash
    container_name: reactor-logstash
    ports:
      - "5044:5044"
      - "5000:5000"
      - "9600:9600"
    networks:
      - reactor-net
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9600 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  kibana:
    build: ./kibana
    container_name: reactor-kibana
    ports:
      - "5601:5601"
    networks:
      - reactor-net
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5601/api/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  filebeat:
    build: ./filebeat
    container_name: reactor-filebeat
    volumes:
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - reactor-net
    depends_on:
      logstash:
        condition: service_healthy

  nginx:
    build: ./nginx
    container_name: reactor-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_logs:/var/log/nginx
    networks:
      - reactor-net
    depends_on:
      - kibana

volumes:
  elasticsearch_data:
    driver: local
  nginx_logs:
    driver: local

networks:
  reactor-net:
    driver: bridge