node.name: "reactor-logstash"
path.data: /usr/share/logstash/data
path.config: /usr/share/logstash/pipeline
path.logs: /usr/share/logstash/logs

# Pipeline settings
pipeline.workers: 2
pipeline.batch.size: 125
pipeline.batch.delay: 50

# Queue settings
queue.type: memory

# Monitoring
monitoring.enabled: true
monitoring.elasticsearch.hosts: ["http://elasticsearch:9200"]
monitoring.elasticsearch.username: "elastic"
monitoring.elasticsearch.password: "ReactorElastic123!"

# Logging
log.level: info
log.format: plain