- pipeline.id: main
  path.config: "/usr/share/logstash/pipeline/main.conf"
  pipeline.workers: 1
  
- pipeline.id: beats
  path.config: "/usr/share/logstash/pipeline/beats.conf"
  pipeline.workers: 1
  
- pipeline.id: zeek
  path.config: "/usr/share/logstash/pipeline/zeek.conf"
  pipeline.workers: 1