server.name: "reactor-kibana"
server.host: "0.0.0.0"
server.port: 5601

elasticsearch.hosts: ["http://elasticsearch:9200"]
elasticsearch.username: "elastic"
elasticsearch.password: "ReactorElastic123!"

# Disable SSL verification (development setup)
elasticsearch.ssl.verificationMode: none

# Monitoring
monitoring.ui.container.elasticsearch.enabled: true

# Security
xpack.security.enabled: true
xpack.encryptedSavedObjects.encryptionKey: "ReactorKibanaEncryptionKey32Chars"
xpack.reporting.encryptionKey: "ReactorKibanaReportingKey32Chars"
xpack.security.encryptionKey: "ReactorKibanaSecurityKey32Chars"

# Saved objects
savedObjects.maxImportPayloadBytes: 26214400

# Logging
logging.appenders.file.type: file
logging.appenders.file.fileName: /usr/share/kibana/logs/kibana.log
logging.appenders.file.layout.type: json
logging.root.level: info